### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by roman901** [pitkley/in-container#30]
Hi! I've tried to build this library on MacOS, but got 
```
expected enum `Option`, found `()`
```
That's because `pub fn get_container_runtime() -> Option<ContainerRuntime>` definition doesn't allow any OSes rather FreeBSD, Linux or Windows.
Can you add default `None` return for MacOS target?

Thanks!

**Comment by pitkley** [comment]
Thanks for reaching out, @roman901. I have implemented the change and published the library as version 1.1.0. Please note that if you previously used

```toml
in-container = "^1"
```

in your `Cargo.toml` that you now should use

```toml
in-container = { version = "^1", default-features = false }
```

instead, which avoids you having to pull in dependencies that in-container only uses for the binary.
